module.exports = {
    'likes': '{ likes, number } me gusta',
    'logout': 'Salir',
    'english': 'Inglés',
    'spanish': 'Español',  
    'italian': 'Italiano',
    'signup.subheading': 'Regístrate para ver fotos de los gatos de tus amigos',
    'signup.facebook': 'Iniciar sesión con Facebook',
    'signup.text': 'Iniciar sesión',
    'email': 'Correo electrónico',
    'username': 'Nombre de usuario',
    'fullname': 'Nombre completo',
    'password': 'Contraseña',
    'signup.call-to-action': 'Regístrate',
    'signup.have-account': '¿Tienes una cuenta?',
    'signin': 'Entrar',
    'signin.not-have-account': '¿No tienes una cuenta?',
    'language': 'Idioma',
    'upload-picture' : ' Subir foto',
    'upload' : 'Upload'
}